name: Generate Streaming M3U8

on:
  schedule:
    - cron: '0 0 * * *'  # Esegue ogni giorno a mezzanotte
  workflow_dispatch:  # Permette esecuzione manuale

jobs:
  generate-m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 fake-headers curl_cffi python-dotenv tmdbv3api

    - name: Create .env file
      env:
        TMDB_KEY: ${{ secrets.TMDB_KEY }}
      run: |
        echo "TMDB_KEY=$TMDB_KEY" > .env

    - name: Run script
      run: python main.py

    - name: Upload M3U8 file
      uses: actions/upload-artifact@v3
      with:
        name: streaming-m3u8
        path: streaming.m3u8
