name: StreamingCommunity Scraper

on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Esegue ogni 15 minuti

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 fake-headers curl_cffi python-dotenv

      - name: Run StreamingCommunity scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python main.py

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add streaming.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true

      - name: Upload M3U8 file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: streaming-m3u8
          path: streaming.m3u8
        continue-on-error: true
